# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Util-DataThing
version:      0.01_01
version_from: lib/Util/DataThing.pm
installdirs:  site
requires:
    Carp:                          0
    MRO::Compat:                   0
    Scalar::Util:                  0
    Sub::Name:                     0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
